version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout

      # Install Node.js
      - node/install

      # Install AWS CLI
      - aws-cli/install

      # Frontend Install
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install

      # Backend Install
      - run:
          name: Install Backend Dependencies
          command: npm run backend:install

      # Frontend Build
      - run:
          name: Build Frontend
          command: npm run frontend:build

      # Backend Build
      - run:
          name: Build Backend
          command: npm run backend:build

      # Frontend Deploy
      - run:
          name: Deploy Frontend
          command: npm run frontend:deploy

      # Backend Deploy
      - run:
          name: Deploy Backend
          command: npm run backend:deploy

workflows:
  build-deploy:
    jobs:
      - build-and-deploy
